export const mechatronicsSubjects = [
    {
        key: "calculo1",
        name: 'Cálculo 1',
        hours: 72,
        completed: false,
        preRequisites: [],
        available: true,
        semester: 1,
    },
    {
        key: "sistemasDigitais",
        name: 'Sistemas Digitais',
        hours: 72,
        completed: false,
        preRequisites: [],
        available: true,
        semester: 1,
    },
    {
        key: "aeds1",
        name: 'AEDS 1',
        hours: 72,
        completed: false,
        preRequisites: [],
        available: true,
        semester: 1,
    },
    {
        key: "quimicaGeral",
        name: 'Química Geral',
        hours: 54,
        completed: false,
        preRequisites: [],
        available: true,
        semester: 1,
    },
    {
        key: "quimicaExperimental",
        name: 'Química Experimental',
        hours: 18,
        completed: false,
        preRequisites: [],
        available: true,
        semester: 1,
    },
    {
        key: "introEngenharia",
        name: 'Introdução à Engenharia',
        hours: 36,
        completed: false,
        preRequisites: [],
        available: true,
        semester: 1,
    },
    {
        key: "metodologiaCientifica",
        name: 'Metodologia Científica',
        hours: 36,
        completed: false,
        preRequisites: [],
        available: true,
        semester: 1,
    },
    {
        key: "calculo2",
        name: 'Cálculo 2',
        hours: 72,
        completed: false,
        preRequisites: ['Cálculo 1'],
        available: false,
        semester: 2,
    },
    {
        key: "fisica1",
        name: 'Física 1',
        hours: 72,
        completed: false,
        preRequisites: ['Cálculo 1'],
        available: false,
        semester: 2,
    },
    {
        key: "aeds2",
        name: 'AEDS 2',
        hours: 72,
        completed: false,
        preRequisites: ['AEDS 1'],
        available: false,
        semester: 2,
    },
    {
        key: "gaal",
        name: 'GAAL',
        hours: 72,
        completed: false,
        preRequisites: [],
        available: true,
        semester: 2,
    },
    {
        key: "individuos",
        name: 'Indivíduos',
        hours: 36,
        completed: false,
        preRequisites: [],
        available: true,
        semester: 2,
    },
    {
        key: "cts",
        name: 'CTS',
        hours: 36,
        completed: false,
        preRequisites: [],
        available: true,
        semester: 2,
    },
    {
        key: "calculo3",
        name: 'Cálculo 3',
        hours: 72,
        completed: false,
        preRequisites: ['Cálculo 1', 'Cálculo 2'],
        available: false,
        semester: 3,
    },
    {
        key: "fisica2",
        name: 'Física 2',
        hours: 72,
        completed: false,
        preRequisites: ['Cálculo 1', 'Física 1'],
        available: false,
        semester: 3,
    },
    {
        key: "poo",
        name: 'POO',
        hours: 72,
        completed: false,
        preRequisites: ['AEDS 1'],
        available: false,
        semester: 3,
    },
    {
        key: "estatistica",
        name: 'Estatística',
        hours: 72,
        completed: false,
        preRequisites: ['Cálculo 1'],
        available: false,
        semester: 3,
    },
    {
        key: "economia",
        name: 'Economia',
        hours: 72,
        completed: false,
        preRequisites: [],
        available: true,
        semester: 3,
    },
    {
        key: "eda",
        name: 'EDA',
        hours: 72,
        completed: false,
        preRequisites: ['Cálculo 1', 'Cálculo 2'],
        available: false,
        semester: 4,
    },
    {
        key: "fisica3",
        name: 'Física 3',
        hours: 72,
        completed: false,
        preRequisites: ['Cálculo 1', 'Física 1'],
        available: false,
        semester: 4,
    },
    {
        key: "calculoNumerico",
        name: 'Cálculo Numérico',
        hours: 72,
        completed: false,
        preRequisites: ['Cálculo 1'],
        available: false,
        semester: 4,
    },
    {
        key: "microprocessadores",
        name: 'Microprocessadores',
        hours: 72,
        completed: false,
        preRequisites: ['Sistemas Digitais'],
        available: false,
        semester: 4,
    },
    {
        key: "materiais",
        name: 'Materiais',
        hours: 72,
        completed: false,
        preRequisites: ['Cálculo 1', 'Física 1'],
        available: false,
        semester: 4,
    },
    {
        key: "edb",
        name: 'EDB',
        hours: 36,
        completed: false,
        preRequisites: ['Cálculo 1', 'Cálculo 2', 'EDA'],
        available: false,
        semester: 5,
    },
    {
        key: "circuitos1teoria",
        name: 'Circuitos 1 - Teoria',
        hours: 72,
        completed: false,
        preRequisites: ['Cálculo 1', 'Cálculo 2', 'EDA'],
        available: false,
        semester: 5,
    },
    {
        key: "circuitos1pratica",
        name: 'Circuitos 1 - Prática',
        hours: 36,
        completed: false,
        preRequisites: ['Cálculo 1', 'Cálculo 2', 'EDA'],
        available: false,
        semester: 5,
    },
    {
        key: "cad1",
        name: 'CAD 1',
        hours: 36,
        completed: false,
        preRequisites: [],
        available: true,
        semester: 5,
    },
    {
        key: "processos",
        name: 'Processos',
        hours: 72,
        completed: false,
        preRequisites: ['Cálculo 1', 'Física 1', 'Materiais'],
        available: false,
        semester: 5,
    },
    {
        key: "estatica",
        name: 'Estática',
        hours: 72,
        completed: false,
        preRequisites: ['Cálculo 1', 'Física 1'],
        available: false,
        semester: 5,
    },
    {
        key: "meioAmbiente",
        name: 'Meio Ambiente',
        hours: 36,
        completed: false,
        preRequisites: [],
        available: true,
        semester: 5,
    },
    {
        key: "modelagem",
        name: 'Modelagem',
        hours: 72,
        completed: false,
        preRequisites: ['Cálculo 1', 'Cálculo 2', 'EDA', 'EDB'],
        available: false,
        semester: 6,
    },
    {
        key: "eletronica1",
        name: 'Eletrônica 1',
        hours: 108,
        completed: false,
        preRequisites: ['Cálculo 1', 'Cálculo 2', 'EDA', 'Circuitos 1 - Teoria'],
        available: false,
        semester: 6,
    },
    {
        key: "cad2",
        name: 'CAD 2',
        hours: 36,
        completed: false,
        preRequisites: ['CAD 1'],
        available: false,
        semester: 6,
    },
    {
        key: "mecanicaDosSolidos",
        name: 'Mecânica dos Sólidos',
        hours: 72,
        completed: false,
        preRequisites: ['Cálculo 1', 'Física 1', 'Estática'],
        available: false,
        semester: 6,
    },
    {
        key: "dinamica",
        name: 'Dinâmica',
        hours: 72,
        completed: false,
        preRequisites: ['Cálculo 1', 'Física 1', 'Estática'],
        available: false,
        semester: 6,
    },
    {
        key: "controle1",
        name: 'Controle 1',
        hours: 72,
        completed: false,
        preRequisites: ['Cálculo 1', 'Cálculo 2', 'EDA', 'EDB', 'Modelagem'],
        available: false,
        semester: 7,
    },
    {
        key: "eletronica2",
        name: 'Eletrônica 2',
        hours: 72,
        completed: false,
        preRequisites: ['Cálculo 1', 'Cálculo 2', 'EDA', 'Circuitos 1 - Teoria', 'Eletrônica 1'],
        available: false,
        semester: 7,
    },
    {
        key: "maquinas",
        name: 'Máquinas',
        hours: 72,
        completed: false,
        preRequisites: ['Cálculo 1', 'Cálculo 2', 'EDA', 'Circuitos 1 - Teoria'],
        available: false,
        semester: 7,
    },
    {
        key: "informaticaIndustrial",
        name: 'Informática Industrial',
        hours: 72,
        completed: false,
        preRequisites: ['Sistemas Digitais', 'Microprocessadores'],
        available: false,
        semester: 7,
    },
    {
        key: "mecanismos",
        name: 'Mecanismos',
        hours: 72,
        completed: false,
        preRequisites: ['Cálculo 1', 'Física 1', 'Estática', 'Mecânica dos Sólidos'],
        available: false,
        semester: 7,
    },
    {
        key: "controle2",
        name: 'Controle 2',
        hours: 72,
        completed: false,
        preRequisites: ['Cálculo 1', 'Cálculo 2', 'EDA', 'EDB', 'Modelagem', 'Controle 1'],
        available: false,
        semester: 8,
    },
    {
        key: "eletronicaDePotencia",
        name: 'Eletrônica de Potência',
        hours: 36,
        completed: false,
        preRequisites: ['Cálculo 1', 'Cálculo 2', 'EDA', 'Circuitos 1 - Teoria', 'Eletrônica 1'],
        available: false,
        semester: 8,
    },
    {
        key: "labMaquinas",
        name: 'Lab. Máquinas',
        hours: 36,
        completed: false,
        preRequisites: ['Cálculo 1', 'Cálculo 2', 'EDA', 'Circuitos 1 - Teoria'],
        available: false,
        semester: 8,
    },
    {
        key: "redesIndustriais",
        name: 'Redes Industriais',
        hours: 72,
        completed: false,
        preRequisites: ['Sistemas Digitais', 'Microprocessadores', 'Informática Industrial'],
        available: false,
        semester: 8,
    },
    {
        key: "mecanicaComputacional",
        name: 'Mecânica Computacional',
        hours: 72,
        completed: false,
        preRequisites: ['Cálculo 1', 'Física 1', 'Estática', 'Mecânica dos Sólidos'],
        available: false,
        semester: 8,
    },
    {
        key: "instrumentacao",
        name: 'Instrumentação',
        hours: 72,
        completed: false,
        preRequisites: ['Cálculo 1', 'Cálculo 2', 'EDA', 'EDB', 'Modelagem'],
        available: false,
        semester: 8,
    },
    {
        key: "controle3",
        name: 'Controle 3',
        hours: 72,
        completed: false,
        preRequisites: ['Cálculo 1', 'Cálculo 2', 'EDA', 'EDB', 'Modelagem', 'Controle 1'],
        available: false,
        semester: 9,
    },
    {
        key: "sistemasEmbarcados",
        name: 'Sistemas Embarcados',
        hours: 72,
        completed: false,
        preRequisites: ['Cálculo 1', 'Cálculo 2', 'EDA', 'Circuitos 1 - Teoria', 'Eletrônica 1'],
        available: false,
        semester: 9,
    },
    {
        key: "optativa1",
        name: 'Optativa 1',
        hours: 72,
        completed: false,
        preRequisites: [],
        available: true,
        semester: 9,
    },
    {
        key: "sistemasSupervisorios",
        name: 'Sistemas Supervisórios',
        hours: 72,
        completed: false,
        preRequisites: ['Sistemas Digitais', 'Microprocessadores', 'Informática Industrial'],
        available: false,
        semester: 9,
    },
    {
        key: "sistemasMecanicos",
        name: 'Sistemas Mecânicos',
        hours: 72,
        completed: false,
        preRequisites: ['Cálculo 1', 'Física 1', 'Estática', 'Mecânica dos Sólidos', 'Dinâmica'],
        available: false,
        semester: 9,
    },
    {
        key: "tcc1",
        name: 'TCC 1',
        hours: 0,
        completed: false,
        preRequisites: [],
        available: true,
        semester: 9,
    },
    {
        key: "robotica",
        name: 'Robótica',
        hours: 72,
        completed: false,
        preRequisites: ['Cálculo 1', 'Cálculo 2', 'EDA', 'EDB', 'Modelagem', 'Controle 1', 'Controle 2'],
        available: false,
        semester: 10,
    },
    {
        key: "optativa2",
        name: 'Optativa 2',
        hours: 72,
        completed: false,
        preRequisites: [],
        available: true,
        semester: 10,
    },
    {
        key: "optativa3",
        name: 'Optativa 3',
        hours: 72,
        completed: false,
        preRequisites: [],
        available: true,
        semester: 10,
    },
    {
        key: "integracaoDeSistemasAutomatizados",
        name: 'Integração de Sistemas Automatizados',
        hours: 72,
        completed: false,
        preRequisites: ['Sistemas Digitais', 'Microprocessadores', 'Informática Industrial', 'Sistemas Supervisórios'],
        available: false,
        semester: 10,
    },
    {
        key: "optativa4",
        name: 'Optativa 4',
        hours: 36,
        completed: false,
        preRequisites: [],
        available: false,
        semester: 10,
    },
    {
        key: "tcc2",
        name: 'TCC 2',
        hours: 36,
        completed: false,
        preRequisites: ['TCC 1'],
        available: false,
        semester: 10,
    },
    {
        key: "estagio",
        name: 'Estágio',
        hours: 200,
        completed: false,
        preRequisites: [],
        available: true,
        semester: 10,
    }
];