import SemesterSubjects from "../src/components/SemesterSubjects";
import { mechatronicsSubjects } from "../src/utils/mechatronicsSubjects";
import { HomeMain } from "../src/styles/home";
import { useState } from "react";
import Head from "next/head";

const Home = () => {
  const [subjects, setSubjects] = useState(mechatronicsSubjects);

  let totoalCoursedHours = 0;

  Object.values(subjects).map(item => {
    if (item.completed) totoalCoursedHours = totoalCoursedHours + item.hours;
  });

  return (
    <>
      <Head>
        <title>Grade Horária</title>
        <meta name="Grade Horária - Engenharia Mecatrônica" content="Generated by create next app" />
      </Head>
      <HomeMain>
        <h1>Estrutura curricular: Engenharia Mecatrônica - UFSJ</h1>
        <div>
          <h3>Carga horária cursada: {totoalCoursedHours}h</h3>
        </div>
        <section>
          <SemesterSubjects semester={1} subjects={subjects} setSubjects={setSubjects} />
          <SemesterSubjects semester={2} subjects={subjects} setSubjects={setSubjects} />
          <SemesterSubjects semester={3} subjects={subjects} setSubjects={setSubjects} />
          <SemesterSubjects semester={4} subjects={subjects} setSubjects={setSubjects} />
          <SemesterSubjects semester={5} subjects={subjects} setSubjects={setSubjects} />
          <SemesterSubjects semester={6} subjects={subjects} setSubjects={setSubjects} />
          <SemesterSubjects semester={7} subjects={subjects} setSubjects={setSubjects} />
          <SemesterSubjects semester={8} subjects={subjects} setSubjects={setSubjects} />
          <SemesterSubjects semester={9} subjects={subjects} setSubjects={setSubjects} />
          <SemesterSubjects semester={10} subjects={subjects} setSubjects={setSubjects} />
        </section>
      </HomeMain>
    </>
  );
};

export default Home;
